# -*- coding: utf-8 -*-
"""Definitivo_HorsesVSHumans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvIvu-EtN8K8UINxu54usEXDh5QI-9Wk
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt

datos,metadatos = tfds.load('horses_or_humans',as_supervised = True, with_info=True)

Dtraindata = datos['train']
testdata = datos['test']

def normalizar(imagenes, etiquetas):
  imagenes = tf.cast(imagenes, tf.float32)
  imagenes /= 255.0 #Aqui se pasa de 0-255 a 0-1
  return imagenes, etiquetas

#Normalizar los datos de entrenamiento con la funcion que hicimos
Dtraindata = Dtraindata.map(normalizar)
testdata = testdata.map(normalizar)

#Preparamos los datos antes de imporimir y operar
import cv2
traindata = []
x = []
y = []
TAMANO_IMG=100
for i, (imagen, etiqueta) in enumerate(datos['train']): #Todos los datos
  imagen = cv2.resize(imagen.numpy(), (TAMANO_IMG, TAMANO_IMG))
  imagen = cv2.cvtColor(imagen, cv2.COLOR_BGR2GRAY)
  imagen = imagen.reshape(TAMANO_IMG, TAMANO_IMG, 1) #Cambiar tamano a 100,100,1
  x.append(imagen)
  y.append(etiqueta)
  traindata.append([imagen, etiqueta])

y = np.array(y)
x = np.array(x).astype(float) / 255

x

plt.figure(figsize=(10,10))
for i in range(25):
  plt.subplot(5,5,i+1)
  plt.xticks([])
  plt.yticks([])
  plt.xlabel(y[i])
  plt.tight_layout()
  plt.imshow(x[i],cmap='gray')

from tensorflow.keras.initializers import HeNormal
modelo = tf.keras.Sequential([
  tf.keras.layers.Conv2D(32, (3,3), activation='relu', kernel_initializer=HeNormal(),input_shape=(100, 100, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3,3),activation='relu'),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2, 2),

  tf.keras.layers.Dropout(0.8),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(250, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

modelo.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

plt.imshow(x[5])

from tensorflow.keras.callbacks import TensorBoard
tensorboard = TensorBoard(log_dir='logs/cnn2')
modelo.fit(x, y, batch_size=32, validation_split=0.2, epochs=3, callbacks=[tensorboard])

from tensorflow.keras.preprocessing import image
def preprocess_image(image_path):
    img = image.load_img(image_path, target_size=(100, 100), color_mode='grayscale')
    img_array = image.img_to_array(img)
    img_array = img_array / 255.0  # Normalizar la imagen
    img_array = np.expand_dims(img_array, axis=0)  # Añadir una dimensión para el batch
    return img_array


image_path = '/content/person22.jpg'


foto = preprocess_image(image_path)

# Realizar la predicción
prediction = modelo.predict(foto)

# Mostrar la predicción
print(f'Model prediction: {prediction[0][0]}')
if prediction[0][0] < 0.5:
    print('Predicted class: Caballo')
else:
    print('Predicted class: Humano')

# Commented out IPython magic to ensure Python compatibility.
#Cargar la extension de tensorboard de colab
# %load_ext tensorboard

# Commented out IPython magic to ensure Python compatibility.
#Ejecutar tensorboard e indicarle que lea la carpeta "logs"
# %tensorboard --logdir logs



from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rotation_range=50,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=[0.7,1.4]
)

datagen.fit(x)
plt.figure(figsize=(10,10))
#Ya nos devuelve un batch de 10, asi que no hace falta iterar
for (foto, etq) in datagen.flow(x,y, batch_size=10, shuffle=False):
  for i in range(10):
    plt.subplot(2,5, i+1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(foto[i].reshape(100,100), cmap='gray')

  plt.tight_layout()
  plt.show()
  break



from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rotation_range=50,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=[0.7,1.4]
)

datagen.fit(x)
plt.figure(figsize=(10,10))
#Ya nos devuelve un batch de 10, asi que no hace falta iterar
for (foto, etq) in datagen.flow(x,y, batch_size=10, shuffle=False):
  for i in range(10):
    plt.subplot(2,5, i+1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(foto[i].reshape(100,100), cmap='gray')

  plt.tight_layout()
  plt.show()
  break

from tensorflow.keras.initializers import HeNormal
modeloAD = tf.keras.Sequential([
  tf.keras.layers.Conv2D(32, (3,3), activation='relu', kernel_initializer=HeNormal(),input_shape=(100, 100, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3,3),activation='relu'),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2, 2),

  tf.keras.layers.Dropout(0.8),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(250, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid')
])
modeloAD.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rotation_range=50,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=[0.7,1.4]
)

datagen.fit(x)
plt.figure(figsize=(10,10))
#Ya nos devuelve un batch de 10, asi que no hace falta iterar
for (foto, etq) in datagen.flow(x,y, batch_size=10, shuffle=False):
  for i in range(10):
    plt.subplot(2,5, i+1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(foto[i].reshape(100,100), cmap='gray')

  plt.tight_layout()
  plt.show()
  break

from tensorflow.keras.initializers import HeNormal
modeloAD = tf.keras.Sequential([
  tf.keras.layers.Conv2D(32, (3,3), activation='relu', kernel_initializer=HeNormal(),input_shape=(100, 100, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3,3),activation='relu'),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2, 2),

  tf.keras.layers.Dropout(0.8),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(250, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid')
])
modeloAD.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

len(x) * .85
len(x) - 873 #

x_train = x[:600]
x_test = x[601:]

y_train = y[:600]
y_test = y[601:]

#Nos devuelve los pares(x,y) del entrenamiento con modificaciones
data_gen_entrenamiento = datagen.flow(x_train,y_train, batch_size=32)
from tensorflow.keras.callbacks import TensorBoard
tensorboardAD = TensorBoard(log_dir='logs/AD')
modeloAD.fit(
    data_gen_entrenamiento,
    batch_size=32,
    validation_data=(x_train,y_train),
    epochs=15,
    steps_per_epoch=int(np.ceil(len(x_train) / float(32))),
    validation_steps=int(np.ceil(len(x_test) / float(32))),
    callbacks=[tensorboardAD])

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir logs

from tensorflow.keras.preprocessing import image
def preprocess_image(image_path):
    img = image.load_img(image_path, target_size=(100, 100), color_mode='grayscale')
    img_array = image.img_to_array(img)
    img_array = img_array / 255.0  # Normalizar la imagen
    img_array = np.expand_dims(img_array, axis=0)  # Añadir una dimensión para el batch
    return img_array


image_path = '/content/person5.jpg'


foto = preprocess_image(image_path)

# Realizar la predicción
prediction = modeloAD.predict(foto)

# Mostrar la predicción
print(f'Model prediction: {prediction[0][0]}')
if prediction[0][0] < 0.5:
    print('Predicted class: Caballo')
else:
    print('Predicted class: Humano')